music_directory         "/srv/music"
playlist_directory      "/var/lib/proaudio-player-alert/mpd/playlists"
db_file                 "/var/lib/proaudio-player-alert/mpd/database"
log_file                "syslog"
pid_file                "/var/lib/proaudio-player-alert/mpd/pid"
state_file              "/var/lib/proaudio-player-alert/mpd/state"
sticker_file            "/var/lib/proaudio-player-alert/mpd/sticker.sql"
bind_to_address         "any"
port                    "6600"
auto_update             "yes"
restore_paused          "yes"

audio_output {
    type                "pulse"
    name                "ProAudio Player Music Bus"
    sink                "proaudio_player_music"
    mixer_type          "software"
}

