general = {
    name = "ProAudio Player";
    output_backend = "pa";
    mdns_backend = "avahi";
    ignore_volume_control = "yes";
    mpris_service_bus = "system";
};

pa = {
    application_name = "ProAudio Player";
    sink = "proaudio_player_music";
};
