general = {
    name = "ProAudio Player";
    output_backend = "pw";
    mdns_backend = "avahi";
    ignore_volume_control = "yes";
    mpris_service_bus = "system";
};

pw = {
    application_name = "ProAudio Player";
    node_name = "proaudio_airplay";
    sink_target = "proaudio_player_music";
};
