[global]
device_name = "ProAudio Player"
device_type = "a_v_r"
backend = "alsa"
device = "proaudio_music"
bitrate = 320
volume_controller = "none"
volume_normalisation = false
normalisation_pregain = 0
cache_path = "/run/proaudio-player/spotifyd"
no_audio_cache = true
zeroconf_port = 0
use_mpris = true
dbus_type = "system"
