[global]
device_name = "ProAudio Player"
device_type = "speaker"
backend = "pulseaudio"
bitrate = 320
volume_controller = "softvol"
volume_normalisation = false
normalisation_pregain = 0
zeroconf_port = 0
no_audio_cache = true
use_mpris = true
dbus_type = "system"
