[global]
device_name = "ProAudio Player"
device_type = "speaker"
backend = "pulseaudio"
bitrate = 320
volume_controller = "softvol"
volume_normalisation = true
normalisation_pregain = -3
zeroconf_port = 0
use_mpris = true
dbus_type = "system"
